name: Theme.API
version: 0.1.10
description: Theme controls the entire UI of any APP.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/theme
environment:
  sdk: '>=2.0.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.0.0 <2.0.0'
  build_web_compilers: '>=1.0.0 <2.0.0'
dependencies:
  mango_ui: '>=0.1.6'